// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx6m55hh2AMWeMf8luGB5E5FAkc9gwNZw',
    appId: '1:621679216977:web:650f6e85e0bf3a257c2b70',
    messagingSenderId: '621679216977',
    projectId: 'blaze-d28fb',
    authDomain: 'blaze-d28fb.firebaseapp.com',
    storageBucket: 'blaze-d28fb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7m4usZh6KP-zCx24Gz8jtKOKvdc3bhmQ',
    appId: '1:621679216977:android:73c540bd165870727c2b70',
    messagingSenderId: '621679216977',
    projectId: 'blaze-d28fb',
    storageBucket: 'blaze-d28fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPh0nE9qS3MXli0_Yt6BoyxvyN0lXcIhI',
    appId: '1:621679216977:ios:50584d35f36b5a777c2b70',
    messagingSenderId: '621679216977',
    projectId: 'blaze-d28fb',
    storageBucket: 'blaze-d28fb.appspot.com',
    iosClientId: '621679216977-6uammgkke1sdu263bq1b5g05ohlsuriu.apps.googleusercontent.com',
    iosBundleId: 'com.example.blaze',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPh0nE9qS3MXli0_Yt6BoyxvyN0lXcIhI',
    appId: '1:621679216977:ios:50584d35f36b5a777c2b70',
    messagingSenderId: '621679216977',
    projectId: 'blaze-d28fb',
    storageBucket: 'blaze-d28fb.appspot.com',
    iosClientId: '621679216977-6uammgkke1sdu263bq1b5g05ohlsuriu.apps.googleusercontent.com',
    iosBundleId: 'com.example.blaze',
  );
}
